import { WORLD_PROP_DEFINITIONS_SHARED, WORLD_TILE_DEFINITIONS_SHARED } from './shared';
import { WORLD_PROP_DEFINITIONS_DUNGEON, WORLD_TILE_DEFINITIONS_DUNGEON } from './dungeon';

export const WORLD_TILE_DEFINITIONS = [
  ...WORLD_TILE_DEFINITIONS_DUNGEON,
  ...WORLD_TILE_DEFINITIONS_SHARED,
];

export const WORLD_PROP_DEFINITIONS = [
  ...WORLD_PROP_DEFINITIONS_DUNGEON,
  ...WORLD_PROP_DEFINITIONS_SHARED,
];
