import { WORLD_PROP_DEFINITIONS_DUNGEON, WORLD_TILE_DEFINITIONS_DUNGEON } from './dungeon';

export const WORLD_TILE_DEFINITIONS = [...WORLD_TILE_DEFINITIONS_DUNGEON];

export const WORLD_PROP_DEFINITIONS = [...WORLD_PROP_DEFINITIONS_DUNGEON];
